/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-06-19 15:12:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1687184593236L));
    _jspx_dependants.put("jar:file:/D:/Zack/FPTU/Courses/SEM_5/SWP391/backup/bknew/DemoProject_1-bk1-Giang/build/web/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Login 05</title>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/accountcreate.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("        <script src=\"https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v17.0&appId=YOUR_APP_ID&autoLogAppEvents=1\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            window.fbAsyncInit = function () {\r\n");
      out.write("                FB.init({\r\n");
      out.write("                    appId: '793594985493909',\r\n");
      out.write("                    xfbml: true,\r\n");
      out.write("                    version: 'v17.0'\r\n");
      out.write("                });\r\n");
      out.write("                FB.AppEvents.logPageView();\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            (function (d, s, id) {\r\n");
      out.write("                var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("                if (d.getElementById(id)) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                js = d.createElement(s);\r\n");
      out.write("                js.id = id;\r\n");
      out.write("                js.src = \"https://connect.facebook.net/en_US/sdk.js\";\r\n");
      out.write("                fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("            }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("        </script>\r\n");
      out.write("        <section class=\"ftco-section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-md-7 col-lg-5\">\r\n");
      out.write("                        <div class=\"wrap\">\r\n");
      out.write("                            <div class=\"img\" style=\"background-image: url(https://img.tgdd.vn/imgt/f_webp,fit_outside,quality_100/https://cdn.tgdd.vn//News/1499962//laptop-20-800x450-2.jpg);\"></div>\r\n");
      out.write("                            <div class=\"login-wrap p-4 p-md-5\">\r\n");
      out.write("                                <div class=\"d-flex\">\r\n");
      out.write("                                    <div class=\"w-100\">\r\n");
      out.write("                                        <h3 class=\"mb-4\">Sign In</h3>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <script>\r\n");
      out.write("                                        function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().\r\n");
      out.write("                                            console.log('statusChangeCallback');\r\n");
      out.write("                                            console.log(response);                   // The current login status of the person.\r\n");
      out.write("                                            if (response.status === 'connected') {   // Logged into your webpage and Facebook.\r\n");
      out.write("                                                testAPI();\r\n");
      out.write("                                            } else {                                 // Not logged into your webpage or we are unable to tell.\r\n");
      out.write("                                                document.getElementById('status').innerHTML = '' +\r\n");
      out.write("                                                        '';\r\n");
      out.write("                                            }\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        function checkLoginState() {               // Called when a person is finished with the Login Button.\r\n");
      out.write("                                            FB.getLoginStatus(function (response) {   // See the onlogin handler\r\n");
      out.write("                                                statusChangeCallback(response);\r\n");
      out.write("                                            });\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        window.fbAsyncInit = function () {\r\n");
      out.write("                                            FB.init({\r\n");
      out.write("                                                appId: '793594985493909',\r\n");
      out.write("                                                cookie: true, // Enable cookies to allow the server to access the session.\r\n");
      out.write("                                                xfbml: true, // Parse social plugins on this webpage.\r\n");
      out.write("                                                version: 'v17.0'           // Use this Graph API version for this call.\r\n");
      out.write("                                            });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            FB.getLoginStatus(function (response) {   // Called after the JS SDK has been initialized.\r\n");
      out.write("                                                statusChangeCallback(response);        // Returns the login status.\r\n");
      out.write("                                            });\r\n");
      out.write("                                        };\r\n");
      out.write("\r\n");
      out.write("                                        function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.\r\n");
      out.write("                                            console.log('Welcome!  Fetching your information.... ');\r\n");
      out.write("                                            FB.api('/me', function (response) {\r\n");
      out.write("                                                console.log('Successful login for: ' + response.name);\r\n");
      out.write("                                                document.getElementById('status').innerHTML =\r\n");
      out.write("                                                        'Thanks for logging in, ' + response.name + '!';\r\n");
      out.write("                                            });\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- The JS SDK Login Button -->\r\n");
      out.write("\r\n");
      out.write("                                    <fb:login-button scope=\"public_profile,email\" onlogin=\"checkLoginState();\">\r\n");
      out.write("                                    </fb:login-button>\r\n");
      out.write("\r\n");
      out.write("                                    <div id=\"status\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <form action=\"login\" class=\"signin-form\" method=\"post\">\r\n");
      out.write("                                    <div class=\"form-group mt-3\"> \r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" required name=\"acname\">\r\n");
      out.write("                                        <label class=\"form-control-placeholder\" for=\"username\">Username</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <input id=\"password-field\" type=\"password\" class=\"form-control\" required name=\"pass\">\r\n");
      out.write("                                        <label class=\"form-control-placeholder\" for=\"password\">Password</label>\r\n");
      out.write("                                        <span toggle=\"#password-field\" class=\"fa fa-fw fa-eye field-icon toggle-password\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"form-control btn btn-primary rounded submit px-3\">Sign In</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group d-md-flex\">\r\n");
      out.write("                                        <div class=\"w-50 text-left\">\r\n");
      out.write("                                            <label class=\"checkbox-wrap checkbox-primary mb-0\">Remember Me\r\n");
      out.write("                                                <input type=\"checkbox\" checked>\r\n");
      out.write("                                                <span class=\"checkmark\"></span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"w-50 text-md-right\">\r\n");
      out.write("                                            <a href=\"Email.jsp\">Forgot Password</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <p class=\"text-center\">Not a member? <a href=\"Register.jsp\">Sign Up</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/popper.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
