/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-06-15 02:12:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Context.*;
import Model.*;
import java.util.*;

public final class Product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1686795093611L));
    _jspx_dependants.put("/jspComponent/cartDropdown.jsp", Long.valueOf(1686795093587L));
    _jspx_dependants.put("jar:file:/D:/Zack/FPTU/Courses/SEM_5/SWP391/backup/bknew/group5-Khangnh/DemoProject_1-bk1/build/web/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/Zack/FPTU/Courses/SEM_5/SWP391/backup/bknew/group5-Khangnh/DemoProject_1-bk1/build/web/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("Context");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        ");

        SupplierDAO supDao = new SupplierDAO();
        List<Supplier> supList = supDao.getAllSupplier();
        List<Cart> carts = new ArrayList<>();
        if (session.getAttribute("Cart") != null) {
            carts = (List<Cart>) session.getAttribute("Cart");
        }
        Product p = (Product) session.getAttribute("p");
        ProductType pt = (ProductType) session.getAttribute("pt");
        
      out.write("\n");
      out.write("\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("\n");
      out.write("        <title>");
      out.print( pt.getPname() );
      out.write("</title>\n");
      out.write("\n");
      out.write("        <!-- Google font -->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,500,700\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- Bootstrap -->\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>\n");
      out.write("\n");
      out.write("        <!-- Slick -->\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/slick.css\"/>\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/slick-theme.css\"/>\n");
      out.write("\n");
      out.write("        <!-- nouislider -->\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/nouislider.min.css\"/>\n");
      out.write("\n");
      out.write("        <!-- Font Awesome Icon -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("        <!-- Custom stlylesheet -->\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("\n");
      out.write("        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("          <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("          <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- HEADER -->\n");
      out.write("        <header>\n");
      out.write("            <!-- TOP HEADER -->\n");
      out.write("            <div id=\"top-header\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <ul class=\"header-links pull-left\">\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-phone\"></i> +021-95-51-84</a></li>\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-envelope-o\"></i> email@email.com</a></li>\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-map-marker\"></i> 1734 Stonecoal Road</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul class=\"header-links pull-right\">\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("   \n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user-o\"></i> My Account</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- /TOP HEADER -->\n");
      out.write("\n");
      out.write("            <!-- MAIN HEADER -->\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <!-- container -->\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <!-- row -->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <!-- LOGO -->\n");
      out.write("                        <div class=\"col-md-3\">\n");
      out.write("                            <div class=\"header-logo\">\n");
      out.write("                                <a href=\"home\" class=\"logo\">\n");
      out.write("                                    <img src=\"./img/logo.png\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /LOGO -->\n");
      out.write("\n");
      out.write("                        <!-- SEARCH BAR -->\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"header-search\">\n");
      out.write("                                <form>\n");
      out.write("                                    <select class=\"input-select\">\n");
      out.write("                                        <option value=\"0\">All Categories</option>\n");
      out.write("                                        <option value=\"1\">Category 01</option>\n");
      out.write("                                        <option value=\"1\">Category 02</option>\n");
      out.write("                                    </select>\n");
      out.write("                                    <input class=\"input\" placeholder=\"Search here\">\n");
      out.write("                                    <button class=\"search-btn\">Search</button>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /SEARCH BAR -->\n");
      out.write("\n");
      out.write("                        <!-- ACCOUNT -->\n");
      out.write("                        <div class=\"col-md-3 clearfix\">\n");
      out.write("                            <div class=\"header-ctn\">\n");
      out.write("                                <!-- Wishlist -->\n");
      out.write("                                <div>\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <i class=\"fa fa-heart-o\"></i>\n");
      out.write("                                        <span>Your Wishlist</span>\n");
      out.write("                                        <div class=\"qty\">2</div>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /Wishlist -->\n");
      out.write("\n");
      out.write("                                <!-- Cart -->\n");
      out.write("                                <div class=\"dropdown\">\n");
      out.write("                                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"true\">\n");
      out.write("                                        <i class=\"fa fa-shopping-cart\"></i>\n");
      out.write("                                        <span>Your Cart</span>\n");
      out.write("                                        ");
 if (carts == null || carts.size()==0) { 
      out.write("\n");
      out.write("                                        <div class=\"qty\">0</div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                        ");
 if (carts != null || carts.size()>0) { 
      out.write("\n");
      out.write("                                        <div class=\"qty\">");
      out.print( carts.size() );
      out.write("</div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </a>\n");
      out.write("                                    <!-- cart dropdown -->\n");
      out.write("                                    ");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"cart-dropdown\">\n");
      out.write("    ");
 if (carts != null && !carts.isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"cart-list\">\n");
      out.write("        <!-- Cart Items -->\n");
      out.write("        ");
 for (Cart c : carts) { 
      out.write("\n");
      out.write("        <div class=\"product-widget\">\n");
      out.write("            <div class=\"product-img\">\n");
      out.write("                <img src=\"");
      out.print( c.getImg() );
      out.write("\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"product-body\">\n");
      out.write("                <h3 class=\"product-name\"><a href=\"#\">");
      out.print( c.getpName() );
      out.write("</a></h3>\n");
      out.write("                <h4 class=\"product-price\"><span class=\"qty\">");
      out.print( c.getQuantity() );
      out.write("x</span>");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
        // /jspComponent/cartDropdown.jsp(18,90) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
        // /jspComponent/cartDropdown.jsp(18,90) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setValue( c.getPrice() );
        // /jspComponent/cartDropdown.jsp(18,90) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setCurrencyCode("VND");
        // /jspComponent/cartDropdown.jsp(18,90) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setMaxFractionDigits(0);
        int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
        _jspx_th_fmt_005fformatNumber_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
      }
      out.write("</h4>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"cart?seri=");
      out.print( c.getSeri() );
      out.write("&delSmall=1\"><button name=\"delSmall\" class=\"delete\"><i class=\"fa fa-close\"></i></button></a>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <!-- Cart Items -->\n");
      out.write("    </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <div class=\"empty-cart-notification\">\n");
      out.write("        Your cart is empty!\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <div class=\"cart-summary\">\n");
      out.write("        <small>");
      out.print( carts.size() );
      out.write(" Item(s) selected</small>\n");
      out.write("        ");
 float total = 0;
            for (Cart c : carts) { 
                total += c.getQuantity() * c.getPrice();
            }
        
      out.write("\n");
      out.write("        <h5>SUBTOTAL: ");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
        // /jspComponent/cartDropdown.jsp(37,22) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setType("currency");
        // /jspComponent/cartDropdown.jsp(37,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setValue( total );
        // /jspComponent/cartDropdown.jsp(37,22) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setCurrencyCode("VND");
        // /jspComponent/cartDropdown.jsp(37,22) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setMaxFractionDigits(0);
        int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
        _jspx_th_fmt_005fformatNumber_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
      }
      out.write("</h5>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"cart-btns\">\n");
      out.write("        <a href=\"cart?btnViewCart=1\">View Cart</a>\n");
      out.write("        <a href=\"#\">Checkout <i class=\"fa fa-arrow-circle-right\"></i></a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Cart -->\n");
      out.write("\n");
      out.write("                                <!-- Menu Toogle -->\n");
      out.write("                                <div class=\"menu-toggle\">\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <i class=\"fa fa-bars\"></i>\n");
      out.write("                                        <span>Menu</span>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /Menu Toogle -->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /ACCOUNT -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- row -->\n");
      out.write("                </div>\n");
      out.write("                <!-- container -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /MAIN HEADER -->\n");
      out.write("        </header>\n");
      out.write("        <!-- /HEADER -->\n");
      out.write("\n");
      out.write("        <!-- NAVIGATION -->\n");
      out.write("        <nav id=\"navigation\">\n");
      out.write("            <!-- container -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- responsive-nav -->\n");
      out.write("                <div id=\"responsive-nav\">\n");
      out.write("                    <!-- NAV -->\n");
      out.write("                    <ul class=\"main-nav nav navbar-nav\">\n");
      out.write("                        <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\">Hot Deals</a></li>\n");
      out.write("                        <li><a href=\"#\">Categories</a></li>\n");
      out.write("                        <li><a href=\"#\">Laptops</a></li>\n");
      out.write("                        <li><a href=\"#\">Smartphones</a></li>\n");
      out.write("                        <li><a href=\"#\">Cameras</a></li>\n");
      out.write("                        <li><a href=\"#\">Accessories</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /NAV -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /responsive-nav -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /container -->\n");
      out.write("        </nav>\n");
      out.write("        <!-- /NAVIGATION -->\n");
      out.write("\n");
      out.write("        <!-- BREADCRUMB -->\n");
      out.write("        <div id=\"breadcrumb\" class=\"section\">\n");
      out.write("            <!-- container -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <ul class=\"breadcrumb-tree\">\n");
      out.write("                            <li><a href=\"#\">Home</a></li>\n");
      out.write("                            <li><a href=\"#\">All Categories</a></li>\n");
      out.write("                            <li><a href=\"#\">Accessories</a></li>\n");
      out.write("                            <li><a href=\"#\">Headphones</a></li>\n");
      out.write("                            <li class=\"active\">");
      out.print( pt.getPname() );
      out.write("</li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- /row -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /container -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /BREADCRUMB -->\n");
      out.write("\n");
      out.write("        <!-- SECTION -->\n");
      out.write("        <div class=\"section\">\n");
      out.write("            <!-- container -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <!-- Product main img -->\n");
      out.write("                    <div class=\"col-md-5 col-md-push-2\">\n");
      out.write("                        <div id=\"product-main-img\">\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /Product main img -->\n");
      out.write("\n");
      out.write("                    <!-- Product thumb imgs -->\n");
      out.write("                    <div class=\"col-md-2  col-md-pull-5\">\n");
      out.write("                        <div id=\"product-imgs\">\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /Product thumb imgs -->\n");
      out.write("\n");
      out.write("                    <!-- Product details -->\n");
      out.write("                    <div class=\"col-md-5\">\n");
      out.write("                        <div class=\"product-details\">\n");
      out.write("                            <h2 class=\"product-name\">");
      out.print( pt.getPname() );
      out.write("</h2>\n");
      out.write("                            <div>\n");
      out.write("                                <div class=\"product-rating\">\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <a class=\"review-link\" href=\"#\">10 Review(s) | Add your review</a>\n");
      out.write("                            </div>\n");
      out.write("                            <div>\n");
      out.write("                                <h3 class=\"product-price\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
        // /Product.jsp(256,58) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f2.setType("currency");
        // /Product.jsp(256,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f2.setValue( p.getPrice() );
        // /Product.jsp(256,58) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f2.setCurrencyCode("VND");
        // /Product.jsp(256,58) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f2.setMaxFractionDigits(0);
        int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
        _jspx_th_fmt_005fformatNumber_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
      }
      out.write("\n");
      out.write("                                    <del class=\"product-old-price\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
        // /Product.jsp(257,67) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f3.setType("currency");
        // /Product.jsp(257,67) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f3.setValue( p.getPrice() );
        // /Product.jsp(257,67) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f3.setCurrencyCode("VND");
        // /Product.jsp(257,67) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f3.setMaxFractionDigits(0);
        int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
        _jspx_th_fmt_005fformatNumber_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
      }
      out.write("</del>\n");
      out.write("                                </h3>\n");
      out.write("                                ");
 
                                    if (pt.getQuantity() > 0) {
                                
      out.write("\n");
      out.write("                                <span class=\"product-available\">In Stock</span>\n");
      out.write("                                ");
 } 
                                    if (pt.getQuantity() == 0) {
                                
      out.write("\n");
      out.write("                                <span class=\"product-available\">Out Of Stock</span>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <p>");
      out.print( pt.getDescribe() );
      out.write("</p>\n");
      out.write("\n");
      out.write("                            <div class=\"add-to-cart\">\n");
      out.write("                                <div class=\"qty-label\">\n");
      out.write("                                    Qty\n");
      out.write("                                    <div class=\"input-number\">\n");
      out.write("                                        <input id=\"quantityInput");
      out.print( p.getSeri() );
      out.write("\" type=\"text\" value=\"1\">\n");
      out.write("                                        <span class=\"qty-up\" onclick=\"incrementValue('");
      out.print( p.getSeri() );
      out.write("')\">+</span>\n");
      out.write("                                        <span class=\"qty-down\" onclick=\"decrementValue('");
      out.print( p.getSeri() );
      out.write("')\">-</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <form action=\"cart\" method=\"post\" style=\"display: inline;\">\n");
      out.write("                                    <button name=\"addToCart\" class=\"add-to-cart-btn\">\n");
      out.write("                                        <i class=\"fa fa-shopping-cart\"></i> add to cart\n");
      out.write("                                    </button>\n");
      out.write("                                    <input hidden name=\"seri\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getSeri()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                                    <input hidden name=\"quantity\" id=\"quantityInputHidden\">\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <ul class=\"product-btns\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart-o\"></i> add to wishlist</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-exchange\"></i> add to compare</a></li>\n");
      out.write("                            </ul>\n");
      out.write("\n");
      out.write("                            <ul class=\"product-links\">\n");
      out.write("                                <li>Category:</li>\n");
      out.write("                                <li><a href=\"#\">Headphones</a></li>\n");
      out.write("                                <li><a href=\"#\">Accessories</a></li>\n");
      out.write("                            </ul>\n");
      out.write("\n");
      out.write("                            <ul class=\"product-links\">\n");
      out.write("                                <li>Share:</li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-envelope\"></i></a></li>\n");
      out.write("                            </ul>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /Product details -->\n");
      out.write("\n");
      out.write("                    <!-- Product tab -->\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <div id=\"product-tab\">\n");
      out.write("                            <!-- product tab nav -->\n");
      out.write("                            <ul class=\"tab-nav\">\n");
      out.write("                                <li class=\"active\"><a data-toggle=\"tab\" href=\"#tab1\">Description</a></li>\n");
      out.write("                                <li><a data-toggle=\"tab\" href=\"#tab2\">Details</a></li>\n");
      out.write("                                <li><a data-toggle=\"tab\" href=\"#tab3\">Reviews (3)</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /product tab nav -->\n");
      out.write("\n");
      out.write("                            <!-- product tab content -->\n");
      out.write("                            <div class=\"tab-content\">\n");
      out.write("                                <!-- tab1  -->\n");
      out.write("                                <div id=\"tab1\" class=\"tab-pane fade in active\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-12\">\n");
      out.write("                                            <p>");
      out.print( pt.getDescribe() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /tab1  -->\n");
      out.write("\n");
      out.write("                                <!-- tab2  -->\n");
      out.write("                                <div id=\"tab2\" class=\"tab-pane fade in\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-12\">\n");
      out.write("                                            <div class=\"container\">\n");
      out.write("                                                <div class=\"laptop-detail\">\n");
      out.write("                                                    <div class=\"detail-item\">\n");
      out.write("                                                        <span class=\"detail-title\">Ram</span>\n");
      out.write("                                                        <span class=\"detail-content\">");
      out.print( pt.getRam() );
      out.write("</span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"detail-item\">\n");
      out.write("                                                        <span class=\"detail-title\">CPU</span>\n");
      out.write("                                                        <span class=\"detail-content\">");
      out.print( pt.getCpu() );
      out.write("</span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"detail-item\">\n");
      out.write("                                                        <span class=\"detail-title\">Hard Drive</span>\n");
      out.write("                                                        <span class=\"detail-content\">");
      out.print( pt.getHarddriver() );
      out.write("</span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"detail-item\">\n");
      out.write("                                                        <span class=\"detail-title\">Screen</span>\n");
      out.write("                                                        <span class=\"detail-content\">");
      out.print( pt.getScreen() );
      out.write("</span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"detail-item\">\n");
      out.write("                                                        <span class=\"detail-title\">Color</span>\n");
      out.write("                                                        <span class=\"detail-content\">");
      out.print( pt.getColor() );
      out.write("</span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /tab2  -->\n");
      out.write("\n");
      out.write("                                <!-- tab3  -->\n");
      out.write("                                <div id=\"tab3\" class=\"tab-pane fade in\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <!-- Rating -->\n");
      out.write("                                        <div class=\"col-md-3\">\n");
      out.write("                                            <div id=\"rating\">\n");
      out.write("                                                <div class=\"rating-avg\">\n");
      out.write("                                                    <span>4.5</span>\n");
      out.write("                                                    <div class=\"rating-stars\">\n");
      out.write("                                                        <i class=\"fa fa-star\"></i>\n");
      out.write("                                                        <i class=\"fa fa-star\"></i>\n");
      out.write("                                                        <i class=\"fa fa-star\"></i>\n");
      out.write("                                                        <i class=\"fa fa-star\"></i>\n");
      out.write("                                                        <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <ul class=\"rating\">\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"rating-stars\">\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"rating-progress\">\n");
      out.write("                                                            <div style=\"width: 80%;\"></div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <span class=\"sum\">3</span>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"rating-stars\">\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"rating-progress\">\n");
      out.write("                                                            <div style=\"width: 60%;\"></div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <span class=\"sum\">2</span>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"rating-stars\">\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"rating-progress\">\n");
      out.write("                                                            <div></div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <span class=\"sum\">0</span>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"rating-stars\">\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"rating-progress\">\n");
      out.write("                                                            <div></div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <span class=\"sum\">0</span>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"rating-stars\">\n");
      out.write("                                                            <i class=\"fa fa-star\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                            <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"rating-progress\">\n");
      out.write("                                                            <div></div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <span class=\"sum\">0</span>\n");
      out.write("                                                    </li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- /Rating -->\n");
      out.write("\n");
      out.write("                                        <!-- Reviews -->\n");
      out.write("                                        <div class=\"col-md-6\">\n");
      out.write("                                            <div id=\"reviews\">\n");
      out.write("                                                <ul class=\"reviews\">\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"review-heading\">\n");
      out.write("                                                            <h5 class=\"name\">John</h5>\n");
      out.write("                                                            <p class=\"date\">27 DEC 2018, 8:0 PM</p>\n");
      out.write("                                                            <div class=\"review-rating\">\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star-o empty\"></i>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"review-body\">\n");
      out.write("                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"review-heading\">\n");
      out.write("                                                            <h5 class=\"name\">John</h5>\n");
      out.write("                                                            <p class=\"date\">27 DEC 2018, 8:0 PM</p>\n");
      out.write("                                                            <div class=\"review-rating\">\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star-o empty\"></i>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"review-body\">\n");
      out.write("                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <div class=\"review-heading\">\n");
      out.write("                                                            <h5 class=\"name\">John</h5>\n");
      out.write("                                                            <p class=\"date\">27 DEC 2018, 8:0 PM</p>\n");
      out.write("                                                            <div class=\"review-rating\">\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                                                <i class=\"fa fa-star-o empty\"></i>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"review-body\">\n");
      out.write("                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </li>\n");
      out.write("                                                </ul>\n");
      out.write("                                                <ul class=\"reviews-pagination\">\n");
      out.write("                                                    <li class=\"active\">1</li>\n");
      out.write("                                                    <li><a href=\"#\">2</a></li>\n");
      out.write("                                                    <li><a href=\"#\">3</a></li>\n");
      out.write("                                                    <li><a href=\"#\">4</a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- /Reviews -->\n");
      out.write("\n");
      out.write("                                        <!-- Review Form -->\n");
      out.write("                                        <div class=\"col-md-3\">\n");
      out.write("                                            <div id=\"review-form\">\n");
      out.write("                                                <form class=\"review-form\">\n");
      out.write("                                                    <input class=\"input\" type=\"text\" placeholder=\"Your Name\">\n");
      out.write("                                                    <input class=\"input\" type=\"email\" placeholder=\"Your Email\">\n");
      out.write("                                                    <textarea class=\"input\" placeholder=\"Your Review\"></textarea>\n");
      out.write("                                                    <div class=\"input-rating\">\n");
      out.write("                                                        <span>Your Rating: </span>\n");
      out.write("                                                        <div class=\"stars\">\n");
      out.write("                                                            <input id=\"star5\" name=\"rating\" value=\"5\" type=\"radio\"><label for=\"star5\"></label>\n");
      out.write("                                                            <input id=\"star4\" name=\"rating\" value=\"4\" type=\"radio\"><label for=\"star4\"></label>\n");
      out.write("                                                            <input id=\"star3\" name=\"rating\" value=\"3\" type=\"radio\"><label for=\"star3\"></label>\n");
      out.write("                                                            <input id=\"star2\" name=\"rating\" value=\"2\" type=\"radio\"><label for=\"star2\"></label>\n");
      out.write("                                                            <input id=\"star1\" name=\"rating\" value=\"1\" type=\"radio\"><label for=\"star1\"></label>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <button class=\"primary-btn\">Submit</button>\n");
      out.write("                                                </form>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- /Review Form -->\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /tab3  -->\n");
      out.write("                            </div>\n");
      out.write("                            <!-- /product tab content  -->\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /product tab -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /row -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /container -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /SECTION -->\n");
      out.write("\n");
      out.write("        <!-- Section -->\n");
      out.write("        <div class=\"section\">\n");
      out.write("            <!-- container -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <div class=\"section-title text-center\">\n");
      out.write("                            <h3 class=\"title\">Related Products</h3>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- product -->\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                        <div class=\"product\">\n");
      out.write("                            <div class=\"product-img\">\n");
      out.write("                                <img src=\"./img/product01.png\" alt=\"\">\n");
      out.write("                                <div class=\"product-label\">\n");
      out.write("                                    <span class=\"sale\">-30%</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-body\">\n");
      out.write("                                <p class=\"product-category\">Category</p>\n");
      out.write("                                <h3 class=\"product-name\"><a href=\"#\">product name goes here</a></h3>\n");
      out.write("                                <h4 class=\"product-price\">$980.00 <del class=\"product-old-price\">$990.00</del></h4>\n");
      out.write("                                <div class=\"product-rating\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"product-btns\">\n");
      out.write("                                    <button class=\"add-to-wishlist\"><i class=\"fa fa-heart-o\"></i><span class=\"tooltipp\">add to wishlist</span></button>\n");
      out.write("                                    <button class=\"add-to-compare\"><i class=\"fa fa-exchange\"></i><span class=\"tooltipp\">add to compare</span></button>\n");
      out.write("                                    <button class=\"quick-view\"><i class=\"fa fa-eye\"></i><span class=\"tooltipp\">quick view</span></button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"add-to-cart\">\n");
      out.write("                                <button class=\"add-to-cart-btn\"><i class=\"fa fa-shopping-cart\"></i> add to cart</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /product -->\n");
      out.write("\n");
      out.write("                    <!-- product -->\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                        <div class=\"product\">\n");
      out.write("                            <div class=\"product-img\">\n");
      out.write("                                <img src=\"./img/product02.png\" alt=\"\">\n");
      out.write("                                <div class=\"product-label\">\n");
      out.write("                                    <span class=\"new\">NEW</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-body\">\n");
      out.write("                                <p class=\"product-category\">Category</p>\n");
      out.write("                                <h3 class=\"product-name\"><a href=\"#\">product name goes here</a></h3>\n");
      out.write("                                <h4 class=\"product-price\">$980.00 <del class=\"product-old-price\">$990.00</del></h4>\n");
      out.write("                                <div class=\"product-rating\">\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"product-btns\">\n");
      out.write("                                    <button class=\"add-to-wishlist\"><i class=\"fa fa-heart-o\"></i><span class=\"tooltipp\">add to wishlist</span></button>\n");
      out.write("                                    <button class=\"add-to-compare\"><i class=\"fa fa-exchange\"></i><span class=\"tooltipp\">add to compare</span></button>\n");
      out.write("                                    <button class=\"quick-view\"><i class=\"fa fa-eye\"></i><span class=\"tooltipp\">quick view</span></button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"add-to-cart\">\n");
      out.write("                                <button class=\"add-to-cart-btn\"><i class=\"fa fa-shopping-cart\"></i> add to cart</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /product -->\n");
      out.write("\n");
      out.write("                    <div class=\"clearfix visible-sm visible-xs\"></div>\n");
      out.write("\n");
      out.write("                    <!-- product -->\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                        <div class=\"product\">\n");
      out.write("                            <div class=\"product-img\">\n");
      out.write("                                <img src=\"./img/product03.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-body\">\n");
      out.write("                                <p class=\"product-category\">Category</p>\n");
      out.write("                                <h3 class=\"product-name\"><a href=\"#\">product name goes here</a></h3>\n");
      out.write("                                <h4 class=\"product-price\">$980.00 <del class=\"product-old-price\">$990.00</del></h4>\n");
      out.write("                                <div class=\"product-rating\">\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\n");
      out.write("                                    <i class=\"fa fa-star-o\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"product-btns\">\n");
      out.write("                                    <button class=\"add-to-wishlist\"><i class=\"fa fa-heart-o\"></i><span class=\"tooltipp\">add to wishlist</span></button>\n");
      out.write("                                    <button class=\"add-to-compare\"><i class=\"fa fa-exchange\"></i><span class=\"tooltipp\">add to compare</span></button>\n");
      out.write("                                    <button class=\"quick-view\"><i class=\"fa fa-eye\"></i><span class=\"tooltipp\">quick view</span></button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"add-to-cart\">\n");
      out.write("                                <button class=\"add-to-cart-btn\"><i class=\"fa fa-shopping-cart\"></i> add to cart</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /product -->\n");
      out.write("\n");
      out.write("                    <!-- product -->\n");
      out.write("                    <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                        <div class=\"product\">\n");
      out.write("                            <div class=\"product-img\">\n");
      out.write("                                <img src=\"./img/product04.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-body\">\n");
      out.write("                                <p class=\"product-category\">Category</p>\n");
      out.write("                                <h3 class=\"product-name\"><a href=\"#\">product name goes here</a></h3>\n");
      out.write("                                <h4 class=\"product-price\">$980.00 <del class=\"product-old-price\">$990.00</del></h4>\n");
      out.write("                                <div class=\"product-rating\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"product-btns\">\n");
      out.write("                                    <button class=\"add-to-wishlist\"><i class=\"fa fa-heart-o\"></i><span class=\"tooltipp\">add to wishlist</span></button>\n");
      out.write("                                    <button class=\"add-to-compare\"><i class=\"fa fa-exchange\"></i><span class=\"tooltipp\">add to compare</span></button>\n");
      out.write("                                    <button class=\"quick-view\"><i class=\"fa fa-eye\"></i><span class=\"tooltipp\">quick view</span></button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"add-to-cart\">\n");
      out.write("                                <button class=\"add-to-cart-btn\"><i class=\"fa fa-shopping-cart\"></i> add to cart</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /product -->\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <!-- /row -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /container -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /Section -->\n");
      out.write("\n");
      out.write("        <!-- NEWSLETTER -->\n");
      out.write("        <div id=\"newsletter\" class=\"section\">\n");
      out.write("            <!-- container -->\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- row -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <div class=\"newsletter\">\n");
      out.write("                            <p>Sign Up for the <strong>NEWSLETTER</strong></p>\n");
      out.write("                            <form>\n");
      out.write("                                <input class=\"input\" type=\"email\" placeholder=\"Enter Your Email\">\n");
      out.write("                                <button class=\"newsletter-btn\"><i class=\"fa fa-envelope\"></i> Subscribe</button>\n");
      out.write("                            </form>\n");
      out.write("                            <ul class=\"newsletter-follow\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- /row -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /container -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /NEWSLETTER -->\n");
      out.write("\n");
      out.write("        <!-- FOOTER -->\n");
      out.write("        <footer id=\"footer\">\n");
      out.write("            <!-- top footer -->\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <!-- container -->\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <!-- row -->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <h3 class=\"footer-title\">About Us</h3>\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>\n");
      out.write("                                <ul class=\"footer-links\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-map-marker\"></i>1734 Stonecoal Road</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-phone\"></i>+021-95-51-84</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-envelope-o\"></i>email@email.com</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <h3 class=\"footer-title\">Categories</h3>\n");
      out.write("                                <ul class=\"footer-links\">\n");
      out.write("                                    <li><a href=\"#\">Hot deals</a></li>\n");
      out.write("                                    <li><a href=\"#\">Laptops</a></li>\n");
      out.write("                                    <li><a href=\"#\">Smartphones</a></li>\n");
      out.write("                                    <li><a href=\"#\">Cameras</a></li>\n");
      out.write("                                    <li><a href=\"#\">Accessories</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"clearfix visible-xs\"></div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <h3 class=\"footer-title\">Information</h3>\n");
      out.write("                                <ul class=\"footer-links\">\n");
      out.write("                                    <li><a href=\"#\">About Us</a></li>\n");
      out.write("                                    <li><a href=\"#\">Contact Us</a></li>\n");
      out.write("                                    <li><a href=\"#\">Privacy Policy</a></li>\n");
      out.write("                                    <li><a href=\"#\">Orders and Returns</a></li>\n");
      out.write("                                    <li><a href=\"#\">Terms & Conditions</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-3 col-xs-6\">\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <h3 class=\"footer-title\">Service</h3>\n");
      out.write("                                <ul class=\"footer-links\">\n");
      out.write("                                    <li><a href=\"#\">My Account</a></li>\n");
      out.write("                                    <li><a href=\"#\">View Cart</a></li>\n");
      out.write("                                    <li><a href=\"#\">Wishlist</a></li>\n");
      out.write("                                    <li><a href=\"#\">Track My Order</a></li>\n");
      out.write("                                    <li><a href=\"#\">Help</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /row -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /container -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /top footer -->\n");
      out.write("\n");
      out.write("            <!-- bottom footer -->\n");
      out.write("            <div id=\"bottom-footer\" class=\"section\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <!-- row -->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12 text-center\">\n");
      out.write("                            <ul class=\"footer-payments\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cc-visa\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-credit-card\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cc-paypal\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cc-mastercard\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cc-discover\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cc-amex\"></i></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <span class=\"copyright\">\n");
      out.write("                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /row -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /container -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /bottom footer -->\n");
      out.write("        </footer>\n");
      out.write("        <!-- /FOOTER -->\n");
      out.write("\n");
      out.write("        <!-- jQuery Plugins -->\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/slick.min.js\"></script>\n");
      out.write("        <script src=\"js/nouislider.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.zoom.min.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("        <script src=\"js/productDetail.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Product.jsp(68,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <li><a href=\"logout\"><i class=\"fa fa-user-o\"></i> Logout</a></li>\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Product.jsp(71,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <li><a href=\"Login.jsp\"><i class=\"fa fa-user-o\"></i> Login</a></li>\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /Product.jsp(74,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acct != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <li><a href=\"manager\"><i class=\"fa fa-user-o\"></i> Manager</a></li>\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Product.jsp(220,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Product.jsp(220,28) '${sessionScope.images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Product.jsp(220,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("img");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                <div class=\"product-preview\">\n");
            out.write("                                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\n");
            out.write("                                </div>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /Product.jsp(232,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Product.jsp(232,28) '${sessionScope.images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Product.jsp(232,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("img");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                <div class=\"product-preview\">\n");
            out.write("                                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\n");
            out.write("                                </div>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
