/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-03-17 14:58:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.shashi.service.impl.*;
import com.shashi.service.*;
import com.shashi.beans.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.shashi.beans");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.shashi.service.impl");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.shashi.service");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Shoping Center</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("<!-- Start the footer Contacts -->\r\n");
      out.write("<!-- <a name=\"contact\"></a> -->\r\n");
      out.write("<div class=\"container-fluid\"\r\n");
      out.write("     style=\"background-color: #454545; color: white; margin-top: 200px;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h3 class=\"text-center\">Contact</h3>\r\n");
      out.write("        <p class=\"text-center\">\r\n");
      out.write("            <em>We love our fans!</em>\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"row test\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <p>Fan? Drop a note.</p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-map-marker\"></span>Bitter Code\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-phone\"></span>Phone: +91\r\n");
      out.write("                    1515151515\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-envelope\"></span>Email:\r\n");
      out.write("                    thebittercode@gmail.com\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-copyright-mark\"></span>\r\n");
      out.write("                    BitterCode - 2023\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                /* Checking the user credentials */
                String userT = (String) session.getAttribute("usertype");
                UserBean u = (UserBean) session.getAttribute("userdata");
                if (userT == null) { //LOGGED OUT
            
      out.write("\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <form action=\"fansMessage\" method=\"post\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("                                   placeholder=\"Name\" type=\"text\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <select class=\"form-control\" id=\"contact\" name=\"contact\">\r\n");
      out.write("                                <option selected disabled>Choose type of contact</option>\r\n");
      out.write("                                <option>Complain</option>\r\n");
      out.write("                                <option>Thanks</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("                                   placeholder=\"Email\" type=\"email\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"phone\" name=\"phone\"\r\n");
      out.write("                                   placeholder=\"Mobile\" type=\"text\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <textarea class=\"form-control\" id=\"comments\" name=\"comments\"\r\n");
      out.write("                              placeholder=\"Comment\" rows=\"5\" required></textarea>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 form-group\">\r\n");
      out.write("                            <button class=\"btn pull-right\" type=\"submit\">Send</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else {
      out.write("\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <form action=\"fansMessage\" method=\"post\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("                                   value=\"");
      out.print( u.getName());
      out.write("\" type=\"text\" required readonly=\"true\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <select class=\"form-control\" id=\"contact\" name=\"contact\">\r\n");
      out.write("                                <option selected disabled>Choose type of contact</option>\r\n");
      out.write("                                <option>Complain</option>\r\n");
      out.write("                                <option>Thanks</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("                                   value=\"");
      out.print( u.getEmail());
      out.write("\" type=\"email\" required readonly=\"true\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"phone\" name=\"phone\"\r\n");
      out.write("                                   value=\"");
      out.print( u.getMobile());
      out.write("\" type=\"text\" required readonly=\"true\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <textarea class=\"form-control\" id=\"comments\" name=\"comments\"\r\n");
      out.write("                              placeholder=\"Comment\" rows=\"5\" required></textarea>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 form-group\">\r\n");
      out.write("                            <button class=\"btn pull-right\" type=\"submit\">Send</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 }
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Contact or about us -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
