/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-03-17 14:58:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.shashi.service.impl.*;
import com.shashi.service.*;
import org.json.JSONObject;
import jakarta.servlet.http.Cookie;
import java.net.URLDecoder;
import java.util.Iterator;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1710679232528L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1710679232528L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.shashi.service.impl");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.shashi.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Logout Header</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("<!--Company Header Starting  -->\r\n");
      out.write("<div class=\"container-fluid text-center\"\r\n");
      out.write("     style=\"margin-top: 45px; background-color: #33cc33; color: white; padding: 5px;\">\r\n");
      out.write("    <h2>Ellison Electronics</h2>\r\n");
      out.write("    <h6>We specialize in Electronics</h6>\r\n");
      out.write("    <p align=\"center\"\r\n");
      out.write("       style=\"color: blue; font-weight: bold; margin-top: 5px; margin-bottom: 5px;\"\r\n");
      out.write("       id=\"message\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Company Header Ending -->\r\n");
      out.write("\r\n");

    Cookie[] cookies = (jakarta.servlet.http.Cookie[]) request.getCookies();
    String cartJson = null;
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if (cookie.getName().equals("cart")) {
                cartJson = URLDecoder.decode(cookie.getValue(), "UTF-8");
                break;
            }
        }
    }

    int count = 0;
    if (cartJson != null) {
        JSONObject cart = new JSONObject(cartJson);
        Iterator<String> keys = cart.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            count += cart.getInt(key);
        }
    }
    /* Checking the user credentials */
    String userType = (String) session.getAttribute("usertype");
    if (userType == null) { //LOGGED OUT

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Starting Navigation Bar -->\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\" style=\"width: 70%\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#myNavbar\">\r\n");
      out.write("                <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp\"><span\r\n");
      out.write("                    class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("                <li><a href=\"index.jsp\">Products</a></li>\r\n");
      out.write("                <li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("                                        data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"index.jsp\">All</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=mobile\">Mobiles</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=tv\">TVs</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=laptop\">Laptops</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=camera\">Camera</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=speaker\">Speakers</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp?type=tablet\">Tablets</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <form class=\"form-inline\" action=\"index.jsp\" method=\"get\" style=\"margin-top: 7px;\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" size=\"20\" name=\"search\"\r\n");
      out.write("                           placeholder=\"Search Items\" required>\r\n");
      out.write("                    <div class=\"input-group-btn\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-danger\" value=\"Search\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li><a href=\"cartDetails.jsp\"\r\n");
      out.write("                       style=\"margin: 0px; padding: 0px;\" id=\"mycart\"><i\r\n");
      out.write("                        data-count=\"");
      out.print(count);
      out.write("\"\r\n");
      out.write("                        class=\"fa fa-shopping-cart fa-3x icon-white badge\"\r\n");
      out.write("                        style=\"background-color: #333; margin: 0px; padding: 0px; padding-bottom: 0px; padding-top: 5px;\">\r\n");
      out.write("                </i></a></li>\r\n");
      out.write("                <li><a href=\"register.jsp\">Register</a></li>\r\n");
      out.write("                <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");

} else if ("customer".equalsIgnoreCase(userType)) { //CUSTOMER HEADER

    int notf = new CartServiceImpl().getCartCount((String) session.getAttribute("username"));

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\" style=\"width: 70%\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#myNavbar\">\r\n");
      out.write("                <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"userHome.jsp\"><span\r\n");
      out.write("                    class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("                <li><a href=\"userHome.jsp\">Products</a></li>\r\n");
      out.write("                <li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("                                        data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"userHome.jsp\">All</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=mobile\">Mobiles</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=tv\">TV</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=laptop\">Laptops</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=camera\">Camera</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=speaker\">Speakers</a></li>\r\n");
      out.write("                        <li><a href=\"userHome.jsp?type=tablet\">Tablets</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <form class=\"form-inline\" action=\"index.jsp\" method=\"get\" style=\"margin-top: 7px;\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" size=\"20\" name=\"search\"\r\n");
      out.write("                           placeholder=\"Search Items\" required>\r\n");
      out.write("                    <div class=\"input-group-btn\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-danger\" value=\"Search\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("                ");

                    if (notf == 0) {
                
      out.write("\r\n");
      out.write("                <li><a href=\"cartDetails.jsp\"> <span\r\n");
      out.write("                        class=\"glyphicon glyphicon-shopping-cart\"></span>Cart\r\n");
      out.write("                </a></li>\r\n");
      out.write("\r\n");
      out.write("                ");

                } else {
                
      out.write("\r\n");
      out.write("                <li><a href=\"cartDetails.jsp\"\r\n");
      out.write("                       style=\"margin: 0px; padding: 0px;\" id=\"mycart\"><i\r\n");
      out.write("                        data-count=\"");
      out.print(notf);
      out.write("\"\r\n");
      out.write("                        class=\"fa fa-shopping-cart fa-3x icon-white badge\"\r\n");
      out.write("                        style=\"background-color: #333; margin: 0px; padding: 0px; padding-bottom: 0px; padding-top: 5px;\">\r\n");
      out.write("                </i></a></li>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">User<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"orderDetails.jsp\">Orders</a></li>\r\n");
      out.write("                        <li><a href=\"userProfile.jsp\">Profile</a></li>\r\n");
      out.write("                        <li><a href=\"./LogoutSrv\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");

} else { //ADMIN HEADER

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\" style=\"width: 70%; max-width: 800px;\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#myNavbar\">\r\n");
      out.write("                <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"adminViewProduct.jsp\"><span\r\n");
      out.write("                    class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("                <li><a href=\"adminViewProduct.jsp\">Products</a></li>\r\n");
      out.write("                <li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("                                        data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp\">All</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=mobile\">Mobiles</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=tv\">Tvs</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=laptop\">Laptops</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=camera\">Camera</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=speaker\">Speakers</a></li>\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp?type=tablet\">Tablets</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <form class=\"form-inline\" action=\"index.jsp\" method=\"get\" style=\"margin-top: 7px;\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" size=\"20\" name=\"search\"\r\n");
      out.write("                           placeholder=\"Search Items\" required>\r\n");
      out.write("                    <div class=\"input-group-btn\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-danger\" value=\"Search\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Admin<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"adminStock.jsp\">Stock</a></li>\r\n");
      out.write("                        <li><a href=\"shippedItems.jsp\">Shipped</a></li>\r\n");
      out.write("                        <li><a href=\"unshippedItems.jsp\">Orders</a></li>\r\n");
      out.write("                        <li><a href=\"addProduct.jsp\">Add Product</a></li>\r\n");
      out.write("                        <li><a href=\"removeProduct.jsp\">Remove Product</a></li>\r\n");
      out.write("                        <li><a href=\"updateProductById.jsp\">Update Product</a></li>\r\n");
      out.write("                        <li><a href=\"./LogoutSrv\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");

    }

      out.write("\r\n");
      out.write("<!-- End of Navigation Bar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String message = request.getParameter("message");
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\"\r\n");
      out.write("			style=\"margin-top: 5px; margin-left: 2px; margin-right: 2px;\">\r\n");
      out.write("			<form action=\"./LoginSrv\" method=\"post\"\r\n");
      out.write("				class=\"col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2\"\r\n");
      out.write("				style=\"border: 2px solid black; border-radius: 10px; background-color: #FFE5CC; padding: 10px;\">\r\n");
      out.write("				<div style=\"font-weight: bold;\" class=\"text-center\">\r\n");
      out.write("					<h2 style=\"color: green;\">Login Form</h2>\r\n");
      out.write("					");

					if (message != null) {
					
      out.write("\r\n");
      out.write("					<p style=\"color: blue;\">\r\n");
      out.write("						");
      out.print(message);
      out.write("\r\n");
      out.write("					</p>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div></div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-12 form-group\">\r\n");
      out.write("						<label for=\"last_name\">Username</label> <input type=\"email\"\r\n");
      out.write("							placeholder=\"Enter Username\" name=\"username\" class=\"form-control\"\r\n");
      out.write("							id=\"last_name\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-12 form-group\">\r\n");
      out.write("						<label for=\"last_name\">Password</label> <input type=\"password\"\r\n");
      out.write("							placeholder=\"Enter Password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("							id=\"last_name\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-12\">\r\n");
      out.write("                                        <p>Haven't got an account? <a href=\"register.jsp\">Register</a></p>\r\n");
      out.write("                                        <a href=\"forgotPassword.jsp\">Forgot Password</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-12 text-center\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shoping Center</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("	<!-- Start the footer Contacts -->\r\n");
      out.write("	<!-- <a name=\"contact\"></a> -->\r\n");
      out.write("	<div class=\"container-fluid\"\r\n");
      out.write("		style=\"background-color: #454545; color: white; margin-top: 200px;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h3 class=\"text-center\">Contact</h3>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<em>We love our fans!</em>\r\n");
      out.write("			</p>\r\n");
      out.write("			<div class=\"row test\">\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<p>Fan? Drop a note.</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-map-marker\"></span>Bitter Code\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-phone\"></span>Phone: +91\r\n");
      out.write("						1515151515\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-envelope\"></span>Email:\r\n");
      out.write("						thebittercode@gmail.com\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"glyphicon glyphicon-copyright-mark\"></span>\r\n");
      out.write("						BitterCode - 2023\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-8\">\r\n");
      out.write("					<form action=\"fansMessage\" method=\"post\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-6 form-group\">\r\n");
      out.write("								<input class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("									placeholder=\"Name\" type=\"text\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-6 form-group\">\r\n");
      out.write("								<input class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("									placeholder=\"Email\" type=\"email\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<textarea class=\"form-control\" id=\"comments\" name=\"comments\"\r\n");
      out.write("							placeholder=\"Comment\" rows=\"5\" required></textarea>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-12 form-group\">\r\n");
      out.write("								<button class=\"btn pull-right\" type=\"submit\">Send</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End of Contact or about us -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
